### ISSUE TITLE
multiple buttons side-by-side on a web form

### ISSUE THREAD

**Issue by dcollett** [unimelb/unimelb-design-system#200]
Using v0.6, having buttons side-by-side on a web form causes jumpy behaviour on the page when hovering over the buttons.

**Comment by waitingallday** [comment]
I've discussed this with @herrweis and we've decided to keep this bug unfixed, as a passive way of preventing this kind of markup. The documentation requires an update to reflect this, but I'll need to push that to the next version.

**Comment by dcollett** [comment]
No worries. I'm now a reformed reset button user and I promise to never use them again, for fear of being swamped with links to articles by usability experts.

**Comment by waitingallday** [comment]
😉 Thanks Dean

**Comment by waitingallday** [comment]
It was easily fixable, as it turns out 😕
