### ISSUE TITLE
Staff Listings

### ISSUE THREAD

**Issue by Woodykiwi** [unimelb/unimelb-design-system#474]
I had a problem with the Staff Listing Min.  When the class "details" is applied to a division, the image and information are pushed across the page.  See example. 

![image](https://cloud.githubusercontent.com/assets/15919118/11262313/b664f642-8ed1-11e5-82cd-297e65b735bd.png)

If the class "details" is omitted from the div, the image displays above the paragraph as seen in the above image.

With the Staff Listing Detailed (round images), if any detail is included beneath the image, it displays in the centre of the page.  See example.
![image](https://cloud.githubusercontent.com/assets/15919118/11262338/299830ac-8ed2-11e5-859f-c96557aa04fa.png)

The two profiles with very little information render correctly.

My Suggestion
I think the Staff Listing Detailed uses reasonably sized images and users would find it even more helpful if the images plus information were set side by side.  Then you could profile staff with a paragraph around the height of the image which would sit better on the page.  It would really be the same as the present Staff Listing Min but with the larger images. 

Where there is a lot of white in an image, it looks a bit odd on the page. Is it possible to add a fine dark border to the image to lift it from the page?

regards
Alan

**Comment by waitingallday** [comment]
Hi Alan, not really sure what you're trying to do with this. Can you give a little more detail - what is the page purpose, where will it sit etc.

If there's a need for a new listing, then we might need to discuss it with @herrweis

**Comment by Woodykiwi** [comment]
Hi Jason

The page is a Research Group page in the Department of Anatomy and Neuroscience. See below:

http://biomedicalsciences.unimelb.edu.au/research2/department-of-anatomy-and-neuroscience/physical-biological-anthropology/_recache

The page presently does not have images or blurbs in the Staff section. The screen shots on GitHub were from the safe edit.

I think the Staff Listing Min, could be much improved if it used slightly bigger images, and if the image was not aligning with some point in the centre of the page.
Bigger images would mean that the corresponding text would fit in the space adjacent to the image.

Hope this helps.  Get back to me if its not clear.

Regards
alan

**Comment by yevek** [comment]
This is also happening on pages using the "inside tab nav" template on MCE. 

![breaking-background](https://cloud.githubusercontent.com/assets/1305804/17314200/cf513302-58a5-11e6-8df9-d6597e2a8e89.png)

**Comment by waitingallday** [comment]
There is a (potential) fix for this in #607

**Comment by yevek** [comment]
this has been fixed in v5.0
