### ISSUE TITLE
Distinguish headings on Degree Structure Pages

### ISSUE THREAD

**Issue by Woodykiwi** [unimelb/unimelb-design-system#486]
On the following page:

http://mdhs-study.unimelb.edu.au/degrees/bachelor-of-biomedicine/degree-structure#degree-structure

When scanning down the page, the headings for the year and the semester are in the same typeface and of the same size and in all-caps.

Can these be done differently so that the headings for the year (e.g. FIRST YEAR CORE SUBJECTS) are readily distinguished from the subheadings (e.g SEMESTER 1)?

We have had feedback from users which specifically mentions this and  we feel that 
[Degree structure.pdf](https://github.com/marcom-unimelb/unimelb-design-system/files/46855/Degree.structure.pdf)

a change is warranted.

Thanks for your help

Alan

**Comment by herrweis** [comment]
Yes you are right, the headlines do not work with the structure you are using. We will look into this.

**Comment by yevek** [comment]
I think this still needs to get looked at. Headings are hard to read.

![headings](https://cloud.githubusercontent.com/assets/1305804/22008337/747e1faa-dcce-11e6-8842-0854d5a23e23.png)

**Comment by axelboc** [comment]
Fixed a few extra things... Still not fond of the whole table and accordion markup, but one thing at a time! 😄 

### Before
<img width="790" alt="screen shot 2017-02-01 at 2 34 44 pm" src="https://cloud.githubusercontent.com/assets/2936402/22494448/b11423c4-e88b-11e6-881f-3e2b9f650765.png">

### After
<img width="825" alt="screen shot 2017-02-01 at 2 33 46 pm" src="https://cloud.githubusercontent.com/assets/2936402/22494449/b114f7e0-e88b-11e6-9a6d-0ee8bfbfe0e6.png">
<img width="807" alt="screen shot 2017-02-01 at 2 33 52 pm" src="https://cloud.githubusercontent.com/assets/2936402/22494450/b1177178-e88b-11e6-9825-8841d23f07ee.png">
