### ISSUE TITLE
Tweet pull-quote

### ISSUE THREAD

**Issue by tblundell** [unimelb/unimelb-design-system#500]
This isn't an issue but more a request/enquiry.
We've had a request to include tweeting of quotes in a page for the occasional blockquote in an article/page. To demonstrate Ive mocked up a quick and dirty example that serves to show the functionality required. 
I have no idea if there is a need for this (do users use these?), if other sites within the uni would utilise this feature, and even if this is something (functionality/content wise) we should encourage? 

http://nas.le.unimelb.edu.au/blundell/demos/tweet-pullquote/
btw: As its just a mockup the 'tweet text' button is not responsive - so best to view the page on a desktop/laptop. And the link only works within the uni (unless your using VPN of course).

**Comment by waitingallday** [comment]
Strange request! We use the standard tweet embed for displaying tweets eg.

http://web.unimelb.edu.au/components/icons/#labels

https://pursuit.unimelb.edu.au/articles/paris-climate-change-deal-the-wrap#update-1450057660-99

Could you have the block quotes published by someone as tweets already and embed them, then take advantage of their embed controls? Seems like a lot of work for a fairly niche use case otherwise - eg. you'd need to limit the block quote text to a tweet length

**Comment by ptagell** [comment]
That's a nice idea. Could also work well on Pursuit?

**Comment by herrweis** [comment]
Is there any evidence that people would use this? Any testing?

**Comment by herrweis** [comment]
Just another unused button. My guess.

**Comment by ptagell** [comment]
mmm...perhaps, but I don't think Medium tends to do much that doesn't work - https://medium.com/@gutanaka/there-is-something-extraordinary-happening-10492495c715#.g54zhpokn

**Comment by tblundell** [comment]
@waitingallday didn't consider simply embedding the tweet. It could be the simple way to go. only issue is it breaks out of the style and also the quote would not be bold/large. 

@herrweis thats what i was wondering to. no idea how regularly this would be used, and potentially more clutter and a reason for users to get distracted from the article.

**Comment by herrweis** [comment]
The style is not the problem — I think @tblundell solved it already (minor styling and mobile adaption is missing) but the point is if it is valuable and will get used. @ptagell your example is a completely different action and function?

**Comment by axelboc** [comment]
Closing this up. It was quite an interesting idea, but too difficult to execute given the need for more UX and design work. I also don't think it would bring enough value to the design system as a whole.
