### ISSUE TITLE
Longer job descriptions in person detailed profiles do not wrap (and probably should as per listings)

### ISSUE THREAD

**Issue by ptagell** [unimelb/unimelb-design-system#598]
#### Expected behaviour

Expect it to behave more like a listing whereby paragraphs wrap.
#### Actual behaviour

Currently a relatively short piece of descriptive text will break the layout forcing developers to insert `<br>` to achieve normal display. 

See without and with br below. 

![screenshot 2016-04-06 14 28 49](https://cloud.githubusercontent.com/assets/150315/14305854/2db4ebe0-fc04-11e5-93e7-b68f92583752.png)
![screenshot 2016-04-06 14 28 40](https://cloud.githubusercontent.com/assets/150315/14305855/2f32689e-fc04-11e5-8073-b495097efb42.png)

**Comment by ptagell** [comment]
Some additional peculiarities.

**Comment by ptagell** [comment]
<img width="1500" alt="ui-prototype 20160406" src="https://cloud.githubusercontent.com/assets/150315/14306538/5fcce95a-fc0b-11e5-9e9c-0a753b3a53d6.png">

Some additional peculiarities.

**Comment by axelboc** [comment]
Ah yeah, this was fixed in the [article footer](http://web.unimelb.edu.au/components/article/) variant but not in the original listing. I'll get onto it once the article footer variant is deprecated (i.e. once it's replaced with the new short variant from Pursuit).
