### ISSUE TITLE
small alignment issue with arrow on small-buttons with arrows

### ISSUE THREAD

**Issue by ptagell** [unimelb/unimelb-design-system#600]
#### Expected behaviour

Button is a few px to high on small buttons

![screenshot 2016-04-07 09 44 28](https://cloud.githubusercontent.com/assets/150315/14336268/718b87c4-fca5-11e5-9869-8883a54c3cd2.png)

Button code being used is:

```
p
        = link_to "More from Media", "#", :class => "button-small with-arrow"
```

**Comment by axelboc** [comment]
The one on web.unimelb works fine. I also tried the same code in Pursuit and it works fine.

<img width="242" alt="screen shot 2016-04-28 at 11 29 34 am" src="https://cloud.githubusercontent.com/assets/2936402/14873000/125fab68-0d35-11e6-8f2b-a32d43c1ac64.png">

**Comment by patpaev** [comment]
I think this might actually be a webfont issue – the arrow aligns correctly with Roboto, but not with the default/fallback font. 

For whatever reason it looks like Paul's webfonts didn't load (you can see that the arrows in your screenshots are different 'fonts' to each other...)

**Comment by yevek** [comment]
Have checked this on Mac and can't find any issue, suggest to close this one off.
- Chrome Version 55.0.2883.95 
- Firefox 50.1.0
- Safari Version 10.0.1
