### ISSUE TITLE
minor map width issue

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/unimelb-design-system#642]
This report came from Siftnoor Singh.

As per the example: http://web.unimelb.edu.au/components/maps/#height-width-and-zoom there is an option to set a data-width value for an embedded map.

I would expect this to be a 'preferred width' - so that on devices with a screen width smaller than the data-width value, the map adjusted to fit.

What happens is that the data-width gets written out as an inline style attribute on the div, which does not adjust to screen width.

Instead of writing fixed values into the div, could it not write a class which was more gracefully responsive?

**Comment by waitingallday** [comment]
This a great point - the `width` is required for the gmaps implementation, but I'm sure we can do better.
