### ISSUE TITLE
Simplify local nav markup

### ISSUE THREAD

**Issue by waitingallday** [unimelb/unimelb-design-system#653]
#### Expected behaviour

Developers should use clean markup, with a `ul` nested within a `ul`, without any extra wrapper
#### Actual behaviour

At the moment, the local nav markup requires child `ul`s to be wrapped within a `<div class="inner">`. The system should do this at page load.
#### Steps to reproduce

N/A

_Not required in the next- round of deploys!_

**Comment by yevek** [comment]
same as #773 which has more detail
