### ISSUE TITLE
Image gallery option without popover images

### ISSUE THREAD

**Issue by dkevey** [unimelb/unimelb-design-system#698]
#### Current behaviour

Image gallery always produces larger popover images. 
#### Enhancement

Would like to have an image gallery option without the larger popover images. This would be handy to display sponsor logos or similar where a full gallery is not required. To hand code this can be quite challenging for simple edit users.

See this request for MCE: https://github.com/marcom-unimelb/matrix-controlled-environment/issues/140

Added bonus if we have options to display different size images (small, medium, larger) as the current layout may be too big for logos.

Current image gallery with popover:
![current-image-gallery](https://cloud.githubusercontent.com/assets/1305804/17580220/4f2eddae-5fe0-11e6-85e3-29b9f6e18ecc.png)

If <a href> is removed it spits out images like this: 
![image-gallery-layout](https://cloud.githubusercontent.com/assets/1305804/17580382/8e64eb84-5fe1-11e6-9623-aa10d260e989.png)

**Comment by yevek** [comment]
Just tried using the listing style, but even with some adjustments to padding on images it's just not as elegant as the gallery. Not sure how you'd deal with images that aren't the same size. 

![listing-images](https://cloud.githubusercontent.com/assets/1305804/17580628/77638e70-5fe3-11e6-805c-1227a1574431.png)

**Comment by axelboc** [comment]
We'll need to come up with a new listing for this. The gallery isn't the right fit, as it loads a lot of extra stuff and is more for images with different ratios. If we're talking logos, I'm sure we can come up with a simple inline-block listing and let them flow nicely (with vertical alignment, as requested in #801).

**Comment by axelboc** [comment]
@dkevey Jason has implemented a simple inline-block listing, typically for logos, to fix #801. It relies on the images' real dimensions and doesn't resize them at all. It also has `vertical-align: middle` on all items and allows for adding very short captions. Does this fit your use case too?

**Comment by dkevey** [comment]
yes @axelboc that is essentially the same thing
