### ISSUE TITLE
default listing style images broken when viewed on mobile device 

### ISSUE THREAD

**Issue by dcollett** [unimelb/unimelb-design-system#702]
#### Expected behaviour

images display in their entirety when viewed on mobile
#### Actual behaviour

Images cut off - max-width:200%, should be max-width:100% ?
#### Steps to reproduce

Resize your browser when viewing this page http://web.unimelb.edu.au/components/listings/

**Comment by waitingallday** [comment]
This behaviour was intended from the start - it was originally used in news listings where the image was never meant to be shown completely, only as visual interest to break up the listing text. You could try using different listing style - ie. the feature listing?

**Comment by waitingallday** [comment]
Sorry, just checked 😄 I don't think there is a listing style that leaves the images at 100%, this has been an issue that comes up from time to time. I don't think it's been logged yet, we could certainly add a new one to cover this.

**Comment by dcollett** [comment]
That would be great, thanks Jason

**Comment by waitingallday** [comment]
Possibly related to #698
