### ISSUE TITLE
Fix image aspect ratio management in listings

### ISSUE THREAD

**Issue by rhyslawry** [unimelb/unimelb-design-system#709]
Images and their aspect ratios are tricky to deal with at the best of times.
It's currently difficult to maintain the same aspect ratio across all images in a listing (http://web.unimelb.edu.au/components/listings/) - Feature Listing 3 Col

**#### Expected behaviour**
http://web.unimelb.edu.au/components/listings/ - All images are aligned and aspect ratios are the same
Great if all images are already the same aspect ratio
Difficult if images are just slightly different shapes & sizes, even if all are rectangular

Success story:
SSIP Initiatives Listing - All images are in the same aspect ratio; these were manually cropped (from memory)
http://ssip.staff.unimelb.edu.au/#initiatives

**#### Actual behaviour**

Currently have to either hard code inline CSS styling (Too hard for most Edit+ users)
Or manually crop the images to be the same aspect ratio (Time consuming)

A few live examples where the issue exists:

**Election Watch** - Page footer - Votecompass image is slightly shorter
http://electionwatch.unimelb.edu.au/

**Filming on Campus** - Image Gallery - Notice image for "Libraries" is just slightly longer than the rest
http://about.unimelb.edu.au/campuses-and-facilities/filming-on-campus#gallery

**Filming on Campus** - (Note: test page under construction) - Images in listing at bottom of page all of different heights
http://about.unimelb.edu.au/campuses-and-facilities/filming-on-campus/about/recent-projects-test/_recache

**#### Suggestion**
Potentially implement an optional aspect ratio class on <img> tags
For use in pages where it's essential images have the same aspect ratio, but images being used are of all shapes & sizes
Example fix using scss: https://css-tricks.com/snippets/sass/maintain-aspect-ratio-mixin/

**#### Reason**
This would be useful for content creators not familiar with hardcoding CSS
Would possibly also be useful for news & events block listings
e.g. Take a look at Election Watch news listing: http://electionwatch.unimelb.edu.au/
Single width blocks - images are all of different heights, which looks strange when directly next to each other (This has been a big source of frustration from content editors)
I think this has been solved on Pursuit? (All images are of same height) https://pursuit.unimelb.edu.au/

**Comment by waitingallday** [comment]
I think this is a great suggestion, thanks Rhys. We'll need to think about the best way to implement this.

**Comment by axelboc** [comment]
I'm almost done refactoring the default listing and the 2 and 3-column feature listings. I'm replacing them with a single new image listing with:

- cleaner, more semantic markup (no `figure`, BEM classes)
- three variants to control the number of columns (4, 3 or 2 on desktop)
- background images with `background-position: cover` for automatic cropping
- fixed ratio for all images (16/10 - 62.5%)

The old listings will still be available, but marked for deprecation. They will be removed in the next version. I'll leave this issue open, as it will still be relevant to block listings; we'll need to refactor those as well.

@rhyslawry, you mention implementing "an optional aspect ratio class". As mentioned above, the new default ratio across all viewport sizes is 16/10. Here is a screenshot:

<img width="1408" alt="screen shot 2017-02-22 at 2 13 49 pm" src="https://cloud.githubusercontent.com/assets/2936402/23195717/28fcb6d4-f909-11e6-99f9-1d7f140cfeab.png">

Do you think there's a need for image listings with other image ratios? It's very easy to do, just want to check that it's actually need, and if so, to know which ratios to add.

**Comment by rhyslawry** [comment]
I don't think my aspect ratio classes idea is necessary anymore, as you guys seem to be fixing the problems one-by-one in different ways.
It's great that now when an image is too tall for a block listing block, it just gets cropped/covered from the bottom, so all images have the same height.
The main problem that remains is when images are too *wide* - i.e. wider than the 16:10 aspect ratio, they don't get covered from the sides which would be great
See this for a (subtle) example: 
![image](https://cloud.githubusercontent.com/assets/15081925/23196278/9edb7be4-f90c-11e6-8972-e602790d5c69.png)

**Comment by axelboc** [comment]
- [ ] default listing
- [ ] feature listing (2 and 3 columns)
- [ ] block listing (news & events)

**Comment by axelboc** [comment]
Background-image solution implemented for block listings in #831
