### ISSUE TITLE
lead class padding when jumpnav is active

### ISSUE THREAD

**Issue by dkevey** [unimelb/unimelb-design-system#730]
#### Expected behaviour

When using **section class="lead"** with **jumpnav** and header images, there should be padding at the top.

https://resources.web.unimelb.edu.au/controlled-environment/templates/landing/header-with-box

<img width="1435" alt="section-lead-issue" src="https://cloud.githubusercontent.com/assets/1305804/18496019/a33bbc7e-7a65-11e6-886e-369776a93beb.png">
#### Actual behaviour

When the jumpnav is active the padding-top of class="lead" is removed. 
#### Steps to reproduce

In our page templates we include **div class="jumpnav"**  code directly under the header. 
<img width="829" alt="page-template" src="https://cloud.githubusercontent.com/assets/1305804/18496087/3a5026ea-7a66-11e6-8c7f-c03049ba787f.png">

Tried moving the jumpnav above header, but it looks like the **ul class="jumpnav"** element is inserted directly above this - when perhaps should be directly below. 
<img width="1430" alt="jumpnav-injection" src="https://cloud.githubusercontent.com/assets/1305804/18496091/53e7100a-7a66-11e6-9d9d-08a183b24bba.png">

**Comment by rothenburycam** [comment]
+1 for this. Just logged a seperate issue in https://github.com/unimelb/matrix-controlled-environment/issues/232 - closed now.

**Comment by rhyslawry** [comment]
+1 for this as well
Important because `<section class="lead">` gets created automatically from the "introductory text" field in the CMS, which is used in a number of page listing templates at the parent level.

@waitingallday @axelboc 
It's the `padding: 0` in the following snippet:
`.jumpnav-active .uomcontent .lead {
    margin: 0 auto;
    padding: 0;
}`

![image](https://cloud.githubusercontent.com/assets/15081925/22764106/c3d34e04-eebc-11e6-8ec5-3eea5cdc216c.png)

**Comment by dkevey** [comment]
Have put in temp override in MCE for this when used with headerless, but need alternate markup to target when used with headers. 

```
.jumpnav-active .uomcontent .lead {
    padding-bottom: 3rem;
 ```
![with-jumpnav](https://cloud.githubusercontent.com/assets/1305804/24891530/b131fe1c-1eb9-11e7-9816-4b50762029ca.png)
![without-jumpnav](https://cloud.githubusercontent.com/assets/1305804/24891529/b1309798-1eb9-11e7-8191-800d582ac0ec.png)

**Comment by dkevey** [comment]
Have also changed this to use `class="lead left"' when used for headers and looks ok, so just jumpnav CSS to be added in

**Comment by axelboc** [comment]
Sorry it took so long... @dkevey you'll be able to remove your override in v7.
