### ISSUE TITLE
Centering Image Gallery with limited images

### ISSUE THREAD

**Issue by gyounger** [unimelb/unimelb-design-system#733]
Hi, reposting this from MCE area of github.

Before:
![ea99e098-6564-11e6-81ce-9fd980883d48](https://cloud.githubusercontent.com/assets/16639864/18620434/bf5c082a-7e55-11e6-9b38-810b510b9a33.png)
Via https://cms.unimelb.edu.au/controlled-environment/tuc/objects/percy-grainger-by-rupert-bunny/_recache

After:
(This has been centered with a class, but it shrinks the gallery and spacing isn't the best.)
![01ae3f7c-6565-11e6-9ab0-7314c03d0a27](https://cloud.githubusercontent.com/assets/16639864/18620439/ccd2db82-7e55-11e6-966a-bfbc8d4fe28c.png)

Not all the galleries on this site will have limited, i.e. 2, images but there are some that will.

thanks
Gav

**Comment by arts-unimelb** [comment]
I have the same problem - how to centre an image gallery with 4 images:
http://arts.unimelb.edu.au/soll/research/current-research-projects/digital-daisy-bates/_recache

**Comment by gyounger** [comment]
Any chance of getting someone to look at this before the 12th October? There is a public launch event for the site then. thanks in advance

**Comment by axelboc** [comment]
Hi @gyounger, I'll have to see with @waitingallday; he'll be back from leave next week.

**Comment by gyounger** [comment]
@axelboc no worries and thanks!

**Comment by gyounger** [comment]
@axelboc friendly reminder on this one :) thanks!

**Comment by axelboc** [comment]
Sorry for the delay @gyounger - there's finally a solution for this in the form of two variant classes: `image-gallery--small` and `image-gallery--medium`. It will be in the v6 release.
