### ISSUE TITLE
web.unimelb versioning problems

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/unimelb-design-system#738]
I just had a user trying to use the code which appeared in the headers page of v1.0 https://web.unimelb.edu.au/releases/v1.0/components/headers/ as raw code pasted into the staff hub. Can't really help some people, but it did raise an interesting issue in providing availability to old versions of the design system.
#### Expected behaviour

Access to older versions of the Design System is fine for support, and historic purposes, however, such pages should have a visible cue and a note that they may not work with the current version of the design system - or something to that effect.

Currently, when you're looking at the page, the only clue that it's not the current version is from the URL, even the breadcrumbs don't provide any context.

I would also expect that such pages could not be found via searching, as this once again may lead a user directly to an outdated page without realising the context of the older version.
#### Actual behaviour

Pages from older releases look exactly the same as the current release, there are no cues that the code may be outdated.

Pages from older releases can be found in Google search results. Should probably use robots.txt to block the /releases/\* path

![screen shot 2016-09-28 at 9 07 15 am](https://cloud.githubusercontent.com/assets/848310/18895185/0aebec22-855b-11e6-9b6d-70e266e08319.png)

**Comment by yevek** [comment]
I think we just need to get these old pages removed from google now.

**Comment by axelboc** [comment]
Looks like they're gone now.

**Comment by axelboc** [comment]
FYI, the old releases are no longer in a sub-folder at web.unimelb. They have their own URL (the unique URL of the deployment on Netlify).
