### ISSUE TITLE
"half" classes don't allow enough room for the search field

### ISSUE THREAD

**Issue by gyounger** [unimelb/unimelb-design-system#740]
Hi, the search icon is cut off.

Before:
![screen shot 2016-09-29 at 2 52 04 pm](https://cloud.githubusercontent.com/assets/16639864/18941560/91d26c84-8655-11e6-8392-66a24ea54aad.png)

With some additional css:
![screen shot 2016-09-29 at 3 02 57 pm](https://cloud.githubusercontent.com/assets/16639864/18941591/d9c60ac8-8655-11e6-8dd7-150a035f440a.png)

CSS hack thanks to Rachid:

<style>
    .uomcontent .half-searchfix svg {margin-left:0 !important; margin-right:0 !important;} 
    </style>

**Comment by yevek** [comment]
what is the page URL that you are using that on @gyounger ?

**Comment by gyounger** [comment]
@yevek that would help, sorry! 
https://cms.unimelb.edu.au/controlled-environment/archives

**Comment by gyounger** [comment]
@yevek moving this site to MCE
http://archives.unimelb.edu.au

**Comment by waitingallday** [comment]
Can I just butt in and point out that the 'half' classes were never intended for this use - they were only meant to allow text beside another component, ie. an image or video. Everything should be laid out in a single column on design system sites.

**Comment by yevek** [comment]
@gyounger  closing this one off as I think the override is sufficient at this time given above comment from @waitingallday
