### ISSUE TITLE
listing component - enhancements

### ISSUE THREAD

**Issue by dkevey** [unimelb/unimelb-design-system#747]
#### Expected behaviour

Request for enhancement to listing components to include correct styling for **title** and **description** (if needed) to introduce or describe listing. Main purpose is for use in MCE container templates so editors don't need to worry about applying appropriate styles to heading and descriptive text.  
#### Actual behaviour
- currently images need to be cropped to exact size for consistency, should have a max crop height wrapping image instead
- title and description should probably be wrapped in a section so that we can apply "alt" class if needed.
- hero listing description text misaligned if not enough text.
#### Steps to reproduce

See screen shots below for examples or this page for available options: https://resources.web.unimelb.edu.au/controlled-environment/components/listing/options/listing-component-options 

![image-sizing](https://cloud.githubusercontent.com/assets/1305804/19542311/ef00ddaa-96b8-11e6-8b75-0802e439a3fc.png)
![hero-listing](https://cloud.githubusercontent.com/assets/1305804/19542310/ef009016-96b8-11e6-8fe0-d4435d55bba5.png)
![nav-block2](https://cloud.githubusercontent.com/assets/1305804/19542308/eeff7b68-96b8-11e6-846f-9c462ae42fc8.png)
![nav-block-1](https://cloud.githubusercontent.com/assets/1305804/19542309/eefffdd6-96b8-11e6-9cf3-bc8115e293ad.png)

**Comment by waitingallday** [comment]
Sorry just coming around to this, I have a gigantic PR that addresses lots of listing issues - you can definitely wrap the text on any listing in a plain old `div` and do what you want to it there. I would suggest adding `class="alt"` on the `li` itself - the text below the image is not padded, but the `li` container is (will include an example in the docs to illustrate this).

I'm going to add some helper classes to allow cropping on the `figure` element to maintain a consistent height.

Hero listings will be left-aligned.

**Comment by axelboc** [comment]
- Cropping is now addressed in #709.
- For the title and description, can you move them outside of the `navigational-block-listing`? This should ensure they stay in the middle of the page. The spacing between the description and the listing is a little more complicated... At this point I wouldn't want to touch it, so I'd recommend using overrides.
- The hero listing text alignment is fixed in #806.
