### ISSUE TITLE
image in calendar (event) asset is misaligned

### ISSUE THREAD

**Issue by dkevey** [unimelb/unimelb-design-system#767]
#### Expected behaviour
Image isn't correctly aligned on Squiz Matrix Calendar assets when event is an all day event (and doesn't show time). 

#### Actual behaviour
Check out .when .range

#### Steps to reproduce
On Chrome Version 54.0.2840.98 & FF  (MAC)
I think I've covered most options of event types on this page:  https://resources.web.unimelb.edu.au/controlled-environment/templates/news-and-events/events

![event-image-alignment](https://cloud.githubusercontent.com/assets/1305804/20547598/58ccf08e-b171-11e6-890c-69a25540dba3.png)

**Comment by axelboc** [comment]
Just a quick note that for all day events, you may want to use `.when` rather than `.when.range`. Just don't put the time in there. The only use case for `.range` is multiple-day events.
