### ISSUE TITLE
New Audio Media class for soundcloud embeds

### ISSUE THREAD

**Issue by FPG-Github** [unimelb/unimelb-design-system#769]
We are seeing people wanting to embed audio streaming from services like soundcloud as well as videos, would be useful to set up an audio media class similar to `<section class="video">` for the embedding of audio streams from soundcloud. 

Currently straight embedded streams look like this:

![soundcloud-embed-raw](https://cloud.githubusercontent.com/assets/4566277/20655126/a73ccb8a-b573-11e6-8d31-2f5fc60c49f9.PNG)

Normal wrapping with media class and sections has no effect, so have to adapt some wrappers to fix the issue, but they aren't very intuitive. 

In the following screen grab, the first three embeds (and titles) are wrapped as:
1.  `<p><iframe></iframe>text</p> `
2.  `<section class="code"><iframe></iframe><p>text</p></section>`
3.  `<figure class="code"><iframe></iframe><figcaption>text</figcaption></figure>`

![soundcloud-embed-wrapped](https://cloud.githubusercontent.com/assets/4566277/20655238/e5381f10-b574-11e6-900a-5aebb8a26301.PNG)

Note the 3rd option strips the spacing for anything under it - so best option is to probably add a audio class that renders similar to the code class in terms of layout. 

Cheers.

**Comment by waitingallday** [comment]
This will likely be implemented as the 2nd option above, but with the label text aligning to the left, ie. a container class that snaps to 900px instead of the default 700px.

**Comment by axelboc** [comment]
Turns out that SoundCloud embeds were already supported, but not documented. I have, however, introduced a new `embed` component to replace the old `video` and `soundcloud` classes, which had some issues. This will be available in v7.
