### ISSUE TITLE
Exhibition Calendar item different colour stripe

### ISSUE THREAD

**Issue by lmaquignaz** [unimelb/unimelb-design-system#771]
We have moved at least three sites to the MCE who are keen Exhibition calendar item uses – Archives: http://archives.unimelb.edu.au/explore/exhibitions; Grainger: https://cms.unimelb.edu.au/controlled-environment/grainger#whats-on, Museums and Collections https://cms.unimelb.edu.au/controlled-environment/grainger#whats-on.
 
At this stage we are telling them to change Events to Exhibitions as a tag so at least that differentiates the entry.  
However it would also be good if the colour strip could also vary to further make a difference.  
 
To these users Exhibitions are their key public showcase mechanism for their collections so extremely important to them both as providing value to their users and to demonstrate the intrinsic value of their collections.  They even go to the extent of keeping all the Past Exhibition entries - Example .
 
Do you know if there is any planning around introducing a separate colour stripe for exhibitions?

**Comment by waitingallday** [comment]
I believe the reason this component was originally designed with only news & events colours was to make the listing easier to digest at a glance - ie. an item in this listing can either be considered as news (past tense) or an event (future). If more colours are introduced into the listing it increases the cognitive load required to decipher what each listing represents.

Not sure how difficult it will be to do this in MCE, but depending on the ratio of exhibitions to events it may be possible to use double-width listings to give them some extra prominence eg.

  http://web.unimelb.edu.au/components/listings/#block-listings-news-and-events

(first and last listings in that URL)

**Comment by lmaquignaz** [comment]
Hi Jason,
The clients use of Exhibition are – to use the logic you outlined behind the News & Events chronological framework,  relates to ongoing so cognitively it makes sense to have another division.

These exhibition lasts for months (at least 6 months) so there is logic behind a clearer differentiation of this calendar listing.  As previously pointed out two of the clients actually want to keep the exhibitions up past their view date as an artefact of significance in relation to their organisation’s work.

A bit of work making the Exhibition item stand out better is well worth it from our point of view as converting to the MCE is not always an easy sell.

Cheers,
Laura

Laura Maquignaz  |  Library Systems  - Project Support Officer
Collection Access & Delivery |  (Academic Services) / University Services
T: +61 3 8344 9571  E: laura.maquignaz@unimelb.edu.au   |  unimelb.edu.au

Note: I work part-time: Tuesday, Wednesday (all day); Thursday half(day)

**Comment by waitingallday** [comment]
Hi Laura,

Sure that seems reasonable, the palette we're working with is quite limited though - 

  http://web.unimelb.edu.au/components/base/#colour-palette

Could probably do

![screen shot 2016-12-13 at 3 07 17 pm](https://cloud.githubusercontent.com/assets/863542/21127996/42ef1078-c14b-11e6-9851-86c8f6d5110f.png)

or

![screen shot 2016-12-13 at 3 14 54 pm](https://cloud.githubusercontent.com/assets/863542/21128000/48739ef6-c14b-11e6-856e-20d67ba01a51.png)

Any opinions @yevek @axelboc ?

**Comment by lmaquignaz** [comment]
Personally I prefer the yellow as it has no obvious resonances eg. red could be seen as stop, urgent.
Cheers,
Laura

Laura Maquignaz  |  Library Systems  - Project Support Officer
Collection Access & Delivery |  (Academic Services) / University Services
T: +61 3 8344 9571  E: laura.maquignaz@unimelb.edu.au   |  unimelb.edu.au

Note: I work part-time: Tuesday, Wednesday (all day); Thursday half(day)

**Comment by yevek** [comment]
I agree with Laura that yellow is preferable over red for same reasons she has stated. Shouldn't be too hard to implement in MCE - but we need to do a bit of testing and can't guarantee it would work in all situations.
