### ISSUE TITLE
Footer: cta vs alt

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/unimelb-design-system#776]
#### Expected behaviour
Footer element should behave the same whether it uses class="cta" or class="alt".

#### Actual behaviour
When using class="alt", footer does not work with jumpnav. Gets pushed to the right.
When using class="cta", footer behaves correctly, clearing the jumpnav.

Given that it really only seems to be a different background colour, I think footer should work with jumpnav regardless. cta, alt, or nothing at all.

**Comment by yevek** [comment]
Currently we have some CSS overrides for footer in MCE. Would be good to address those as well.

```
/* fix padding in local site footer */

.uomcontent footer.cta .center {margin: 0 auto; padding: 0;}
.uomcontent footer.cta ul.quicklinks {max-width: 100%;}
.uomcontent footer.cta ul.quicklinks li {padding: 0px;}
.uomcontent footer.cta ul.site-links li {padding: 0px;}
.uomcontent [role="main"] footer {padding-bottom: 0rem;}
```
