### ISSUE TITLE
.half em is display block instead of inline

### ISSUE THREAD

**Issue by rhyslawry** [unimelb/unimelb-design-system#777]
#### Expected behaviour
Trying to italicise text the correct way using `<em` within a two column layout (div class="half")
Expect the text in the div to just be italic

#### Actual behaviour
`<em>` is rendering as inline text with fontsize=13px instead of 16, padding at the bottom and display:block instead of inline
Results in italic text that has weird spacing and is on its own line for some reason
Speculated with Jason that it may be for image captions, or trying to emulate some sort of section class="lead" for two columns, but we don't know why this was done.

#### Steps to reproduce
See this screenshot:
![image](https://cloud.githubusercontent.com/assets/15081925/21877149/34e7f8e2-d8dd-11e6-92d8-44a63c6ce534.png)
(Specifically the top line under the heading, and the second to last line. Should all be inline

Have resorted to using `<i>` tags instead like it's 1999 again

**Comment by yevek** [comment]
Another example that will affect the upcoming **Text-area Content Container**.

![em-issue](https://cloud.githubusercontent.com/assets/1305804/22006286/ec0e4326-dcbd-11e6-914a-64562cf79fea.png)

**Comment by waitingallday** [comment]
I tracked this down to a (much older) version of the injection that used `<em>` to contain a button, will remove this in the next release.
