### ISSUE TITLE
Blockquotes out of alignment inside div class="article"

### ISSUE THREAD

**Issue by rhyslawry** [unimelb/unimelb-design-system#780]
#### Expected behaviour
Blockquotes should be aligned the same way in both an article page and a standard page.
i.e. Left aligned to match up with the rest of the text

#### Actual behaviour
Blockquotes are out of alignment with the rest of the text in article pages
Blockquotes have the following css:
`margin: 0 auto;`
Which seems to be causing them to be aligned to the center of their wrapping div.
Problem is, `div class="article"` and a regular divs have different widths. (Why?)
Regular divs 

See incorrect alignment screenshot here:
![blockquote-article](https://cloud.githubusercontent.com/assets/15081925/22043104/35d40c4e-dd62-11e6-8302-1f73c4ebb74e.PNG)

Compare with correctly aligned blockquote within a standard page here:
![blockquote-standardpage](https://cloud.githubusercontent.com/assets/15081925/22043115/445e0436-dd62-11e6-8c4a-1a3dea64a0a6.PNG)

#### Steps to reproduce
See screenshots above

Bad alignment URL: http://capim.unimelb.edu.au/news-events-media/news/taking-a-fish-out-of-water-how-it-can-assist-conservation-efforts
(Outer wrapper is `div class="article"`)
(URL May not be out of alignment anymore by the time you read this as I'm about to use inline styling to realign)
Good alignment URL: http://law.unimelb.edu.au/alumni/mls-news/issue-16-october-2016/a-leader-in-australian-law-reform
(Outer wrapper is regular div)

**Comment by dkevey** [comment]
FYI - this page template in MCE requires `div class="article"` so it might be easier if I put an override in our CSS to reset left margin to 0px ?

**Comment by rhyslawry** [comment]
![image](https://cloud.githubusercontent.com/assets/15081925/22044036/b4298b1a-dd66-11e6-8261-3bb6a9fbc306.png)

Looks like including
`.article blockquote` to this part of the css will set its margin-left: 0 and fix the alignment issue

**Comment by waitingallday** [comment]
I've got a fix for this in the next release, but just quickly that example from above "Taking a fish out of water" is a tricky one though - I would argue that this layout should not be used, as it's offsetting the entire page to the right for the benefit of a date and a couple of share links. We may need to provide a better article sample layout..
