### ISSUE TITLE
Refactor notices

### ISSUE THREAD

**Issue by axelboc** [unimelb/unimelb-design-system#783]
I've always found it confusing that the component is called `notice` but the classes start with `alert-`. An alert to me is what you get when you call `alert('woop woop');`, so I reckon we should rename the classes to `notice-`.

Also, removing the mixins and introducing a bit of BEM would be nice. Something like:

```
.notice /*  blue/info by default */
.notice.notice--success
.notice.notice--warning
.notice.notice--danger
```

**Comment by waitingallday** [comment]
Fixed by #782
