### ISSUE TITLE
Course Header Short - Heading 1 not left aligned

### ISSUE THREAD

**Issue by rhyslawry** [unimelb/unimelb-design-system#784]
#### Expected behaviour
Course Header Short - Headings should be left aligned as per web.unimelb
(Had a question from a faculty about why their heading and subheading on Bespoke courses are out of alignment, it's actually happening across all courses throughout Bespoke)

#### Actual behaviour
In Bespoke, within the "Course Header Short" template, the `<h1>` has a left margin due to it inheriting `margin: 0 auto;` from `.uomcontent [role=main] header h1`
Web.unimelb displays headings for that template as being left aligned, however the example given is using a h2, whereas Bespoke outputs a h1 for the course title, which has not been left aligned.

`<h2>` within `.course-select` has been left aligned, but `<h1>` hasn't
![image](https://cloud.githubusercontent.com/assets/15081925/22084022/91efdf7e-de22-11e6-8b7e-c5516080ee7e.png)

#### Steps to reproduce
See non-aligned example: (Which is a `<h1>`)
http://mdhs-study.unimelb.edu.au/degrees/bachelor-of-biomedicine/overview
![header-nonaligned-bespoke](https://cloud.githubusercontent.com/assets/15081925/22083936/2ce8c5b4-de22-11e6-85fb-fb55bc4e1b33.PNG)

Web.unimelb aligned: (Which is a `<h2>`)
http://web.unimelb.edu.au/components/headers#course-header-short
![image](https://cloud.githubusercontent.com/assets/15081925/22083901/120667c4-de22-11e6-9d22-03409d784252.png)

**Comment by waitingallday** [comment]
I can see what happened here - the original style was built around the use of `h2` but we've probably received SEO advice that the heading should be a `h1`. Will see what I can do about this from the bespoke end as well!

**Comment by waitingallday** [comment]
This has been fixed on bespoke
