### ISSUE TITLE
Block listing new style

### ISSUE THREAD

**Issue by dkevey** [unimelb/unimelb-design-system#794]
#### Expected behaviour
Found this modified block listing style on Law http://law.unimelb.edu.au/alumni/mls-news I quite like what it's trying to achieve and could be reused for other purposes.

Needs a bit of tweaking to: 
- get images responsive
- issue name needs styling (meta field)
- green highlight at bottom should be different colour?

![blocklisting-style](https://cloud.githubusercontent.com/assets/1305804/22360832/da8a54c2-e4a7-11e6-972f-931597042a5e.png)

**Comment by axelboc** [comment]
This should be covered by the new logo listing, as long as the size of the images can be controlled (the logo listing doesn't resize or crop images at all).

**Comment by dkevey** [comment]
Closing this issue off as the image gallery will be released with the fixes to v6.0.1 that will be going in tomorrow
