### ISSUE TITLE
Staff Listing Images

### ISSUE THREAD

**Issue by cmcgrane** [unimelb/unimelb-design-system#816]
#### Expected behaviour
I'm trying to create a list of our Executive Committee using the Staff Listing Detailed template. The images are all different sizes because they're coming from various sources. I'm in the Melbourne Energy Institute, one of the research institutes at the University.

#### Actual behaviour
Images are appearing with ovals behind them, the design system does not automatically resize images and creates a bit of a mess on the page (see below). Do I need to resize the images to a particular size in order for them to fit into the template?

#### Steps to reproduce
![screen shot 2017-02-28 at 2 49 55 pm](https://cloud.githubusercontent.com/assets/26077857/23390937/33b970c4-fdc5-11e6-8844-0323f0575ed0.png)

**Comment by waitingallday** [comment]
Hi,

The oval is actually supposed to be a circle, on a square dimension image. Yes, you will need to resize the images manually if you want to use this particular component/style combo. There is no good way of automatically cropping & resizing profile images - there are just too many variations in the source material, so I would always recommend careful image selection and sizing before building the page.

@dkevey might have more suggestions.

**Comment by cmcgrane** [comment]
Thank you!

So I need to resize them into squares?

**Comment by waitingallday** [comment]
Yes, sorry. It really should say that on the documentation page!

**Comment by cmcgrane** [comment]
Is there any way of ensuring the circles will be the same size?

**Comment by waitingallday** [comment]
Yes, by using the same size images for all profiles on the page. They should be at least 160x160 px, and the styles impose a maximum of 200x200 px (devices with a higher pixel density, eg. retina screens, will benefit from images that are 320x320 px). So what I'd suggest is

1. crop original images to square
2. resize down to 320x320

**Comment by cmcgrane** [comment]
Thanks very much, that's helped enormously!
