### ISSUE TITLE
Ampersand not displaying correctly

### ISSUE THREAD

**Issue by daphaneng** [unimelb/unimelb-design-system#827]
Hey team,

Just noticed that ampersands don't display correctly on our sites. So far I've noticed it on our banners and news section.

![screen shot 2017-03-08 at 11 28 02 am](https://cloud.githubusercontent.com/assets/26263389/23684400/baf99766-03f2-11e7-8ac0-38acfc95f8e7.png)
![screen shot 2017-03-08 at 11 37 28 am](https://cloud.githubusercontent.com/assets/26263389/23684563/a3a96bd0-03f3-11e7-8ee3-ca64bb03054a.png)

**Comment by waitingallday** [comment]
Hi Daph, this will be something specific to how bespoke renders those pages, the design system doesn't do anything at this level. Will pass this on to the bespoke guys.

**Comment by daphaneng** [comment]
Ah okay! Thanks Jason.
