### ISSUE TITLE
Fix links in Design System global footer

### ISSUE THREAD

**Issue by rhyslawry** [unimelb/unimelb-design-system#851]
Please change the following links in the global footer:

### Emergency Information:
http://safety.unimelb.edu.au/emergency
### Disclaimer & Copyright:
http://www.unimelb.edu.au/governance/disclaimer
### Accessibility:
http://www.unimelb.edu.au/accessibility
### Privacy:
http://www.unimelb.edu.au/governance/compliance/privacy

They're all being served by redirects currently.
One of the redirects (the emergency one) actually expired recently (>12 months old) and resulted in a broken emergency link 😨

**Comment by axelboc** [comment]
I'll need to update the legacy injection as well.

**Comment by axelboc** [comment]
The links will be updated once the old design versions are invalidated in the CDN, so probably in a couple of days.
