### ISSUE TITLE
Simple listing component padding issue

### ISSUE THREAD

**Issue by dkevey** [unimelb/unimelb-design-system#852]
#### Expected behaviour
In v6.0.1 the simple listing component has no padding on unordered list. Previously there was either padding or was wrapped in section tag.

#### Actual behaviour
Currently list is hard up against header and needs space.
See: http://arts.unimelb.edu.au/ltrc/consultancies
![without-section-tag](https://cloud.githubusercontent.com/assets/1305804/24843292/b47f548c-1de4-11e7-84f7-65bc05d87fd1.png)

If a section tag is added the padding around h3 and paragraph text is lost.

![with-section-tag](https://cloud.githubusercontent.com/assets/1305804/24843284/a42c1818-1de4-11e7-9fba-b7a6af9e1c5a.png)

#### Steps to reproduce
I can add in a temporary override once issue has been sighted and advice on padding to use.

**Comment by axelboc** [comment]
#863 was a duplicated of this issue, which I've fixed. The fix will go live in v7.
