### ISSUE TITLE
Long caption breaks 'figures floating'

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/unimelb-design-system#881]
#### Expected behaviour
Image captions should wrap at approximately the width of the image. 

#### Actual behaviour
Long image captions wrap eventually, but not before ruining the layout.

#### Steps to reproduce
Insert a long caption on a floated image ;-)

Observe screengrab below
![screen shot 2017-05-18 at 3 28 29 pm](https://cloud.githubusercontent.com/assets/848310/26187839/fd846cd6-3bde-11e7-9514-d16ff3fddf53.png)

**Comment by axelboc** [comment]
I've fixed it on Pursuit, so shouldn't be a problem ;)

**Comment by axelboc** [comment]
Well, I've gone a bit overboard on this... I created a whole new `figure` component. It fixes this issue, of course, but it also brings a whole lot of features and improvements... Hopefully we can bring a bit more consistency to the use of images, videos, etc. across the design system sites.
