### ISSUE TITLE
Harmonise title attributes and metadata

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/unimelb-design-system#894]
#### Expected behaviour
When setting a custom title attribute, I'd expect to see this reflected in all places that display a title attribute: The title tag, meta title, og:title, and twitter:title

#### Actual behaviour
Currently, the custom title attribute %globals_asset_metadata_Title% is only displayed in the title tag, the others still refer to %globals_asset_name%

#### Steps to reproduce
Use %globals_asset_metadata_Title% to populate all instances of a title attribute.

**Comment by axelboc** [comment]
Hehe wrong repo? 😉

**Comment by woowoowoo** [comment]
D'oh!! Second time in a week!
