### ISSUE TITLE
Filtered listing component section text disappearing

### ISSUE THREAD

**Issue by dcollett** [unimelb/unimelb-design-system#896]
#### Expected behaviour
Using the filtered listing template with viewports below 768 width, section text moves above the coloured type boxes, like in this example:

http://science-courses.unimelb.edu.au/study/degrees 

#### Actual behaviour
Using the filtered listing template with viewports below 768 width, section text disappears behind the coloured type boxes. 

#### Steps to reproduce
Happens in MCE & static HTML examples below:

https://cms.unimelb.edu.au/controlled-environment/le/lodge-course-filter/_nocache 
http://nas.le.unimelb.edu.au/dcollett/lodge-matrix/demo/
https://web.unimelb.edu.au/components/filtered-listings/

**Comment by axelboc** [comment]
Wow, this has been broken for a while... There's an override in Bespoke apparently. I'll try to get it fixed tomorrow and push it onto v7.0.
