### ISSUE TITLE
Pathfinder heights not consistent in responsive view

### ISSUE THREAD

**Issue by rothenburycam** [unimelb/unimelb-design-system#902]
#### Expected behaviour
Pathfinder heights should be consistent whether in a single row or two rows 

#### Actual behaviour
Pathfinders are not forced to the same height when broken over more than a single row

#### Steps to reproduce
Example page here: https://cms.unimelb.edu.au/controlled-environment/learn (Currently in development)

![pahtfinder-learn](https://user-images.githubusercontent.com/11714609/27850634-4a4e4d90-6199-11e7-8f81-e543bc8956bb.jpg)

**Comment by axelboc** [comment]
Sorry, the pathfinder boxes are really not meant to be laid out on multiple rows. The broken link on the docs page used to point to page that explained that and recommended using another listing component. I'll add this back into the docs when I can.

**Comment by rhyslawry** [comment]
Hey @axelboc, I've also noticed the `pathfinder-4`'s break-point is a width of **1400px** - Below which it splits into two rows.
The `pathfinder-3`'s responsive breakpoint is only 769px, after which it breaks out into a single column.
Most people viewing pages on laptops have a screen width below 1400px, the most common being around 1280px, casing them to see an ugly two-row version of the pathfinder on all sites. (see examples below)

I agree that the pathfinder looks bad when it's split over two rows. Does this suggest we should lower the `pathfinder-4`'s responsive breakpoint to be something more reasonable like 1200px?

Happy to put this as a new issue if need-be
See below:

\>1400px wide: (1410px)
![image](https://user-images.githubusercontent.com/15081925/27890346-73032e58-6235-11e7-8ec0-fb5062600c58.png)

<1400px wide: (1350px)
![image](https://user-images.githubusercontent.com/15081925/27890364-814ba472-6235-11e7-8acc-1a7b88facbb6.png)


e.g. This is what http://science.unimelb.edu.au/#courses looks like on my small laptop screen:
![image](https://user-images.githubusercontent.com/15081925/27891185-973d905a-623b-11e7-82b7-575a30fc2752.png)

When it would look much better like this: (exact same width screen)
![image](https://user-images.githubusercontent.com/15081925/27891221-e17f1756-623b-11e7-9c4b-636c84a7ddc3.png)

This was achieved by changing the `min-width` from `1400px` to `1200px`:
![image](https://user-images.githubusercontent.com/15081925/27891271-371e97c2-623c-11e7-8cf8-b26916cddb9e.png)

**Comment by axelboc** [comment]
Hmm yeah, no harm in tweaking the breakpoint a little. Do you mind creating a separate issue to avoid any confusion? Thanks.

Off topic, but in my very subjective opinion, four boxes is already too much. The goal is to help users find their path, and I think having four boxes makes that quite difficult (there's too much to scan). Having a featured box in there can alleviate this issue a bit, but it looks really bad below 1400px...

**Comment by rhyslawry** [comment]
Opened issue https://github.com/unimelb/unimelb-design-system/issues/903

**Comment by rothenburycam** [comment]
@axelboc This is just using a content template in Matrix Controlled Environemnt - shouldn't it default to single pathfinder per row in responsive given what you're saying?

**Comment by axelboc** [comment]
Ah yes indeed, I'll raise it with @dkevey. Thanks!

**Comment by axelboc** [comment]
@rothenburycam sorry I misunderstood your initial issue. I could adjust the height of the boxes at that breakpoint, or use flexbox to make every box on each row the same height, but it seems to me like it would solve the wrong problem: the length of the content is the real issue I think. Any chance you can edit it down, or move some of it to the target page?
