### ISSUE TITLE
Background Image for the feature with pathfinders in "Our History" page takes too long to load

### ISSUE THREAD

**Issue by rock-san** [unimelb/unimelb-design-system#905]
#### Expected behaviour
Background Image for the feature with pathfinders should either be loaded before the user gets to that section of the page or be lazy loaded so it appears all at once

#### Actual behaviour
Page is visited and there is no background image for awhile, looks like the background image is missing at first. After awhile the image will start to load bit by bit.

#### Steps to reproduce
Clear cache (if background image has already been loaded) and go here: http://cms.unimelb.edu.au/controlled-environment/about/our-history

**Comment by dkevey** [comment]
Hi @rock-san this site is not live yet to the public and therefore not cached on the Squiz CDN. Once the site is live it should load faster. Can you find any examples on sites that are live? i.e not using the URL starting with http://cms.unimelb.edu.au ?

**Comment by axelboc** [comment]
Reducing the size of the image in production should help as well. It currently is more than 5600px wide, so it can probably be about three times smaller.

**Comment by axelboc** [comment]
Also, since it's not in the foreground, the image can probably be compressed a fair bit. Anyway, closing this now, as it is more of a content issue. Well spotted, though!
