### ISSUE TITLE
Embed videos being cropped when inside a section

### ISSUE THREAD

**Issue by ppteixeira** [unimelb/unimelb-design-system#911]
#### Expected behaviour
Embed videos width are being cropped when they are inside a section tag

#### Actual behaviour
How the design system actually behaves.

#### Steps to reproduce
Include as much information as possible - e.g. browser, URL, screenshots, etc.
Before changing `.video` to `.embed`
```
section
  h2.title Professor Lawrence Krauss on the Origins of the Universe
  .video
    iframe width="560" height="315" src="https://www.youtube.com/embed/7cIbfbl8124" frameborder="0" allowfullscreen
```

After Change
```
section
  h2.title Professor Lawrence Krauss on the Origins of the Universe
  figure.figure.figure--embed
    .embed.figure__content
      iframe width="560" height="315" src="https://www.youtube.com/embed/7cIbfbl8124" frameborder="0" allowfullscreen
```
---
The properties are being overwritten by section's properties:

![screen shot 2017-08-04 at 2 18 59 pm](https://user-images.githubusercontent.com/18137916/28954180-9b5d5390-7920-11e7-862e-1b1e1532ed4c.png)

**Comment by axelboc** [comment]
Fixed with #914
