### ISSUE TITLE
images misaligned in news articles

### ISSUE THREAD

**Issue by dcollett** [unimelb/unimelb-design-system#921]
#### Expected behaviour
Images using the new figure component within <articles> align correctly using v7 of the design system

#### Actual behaviour
Images using the new figure component within <articles> are misaligned

#### Steps to reproduce
See:
https://le.unimelb.edu.au/news/mooc-of-the-month-september-2017/

This page uses the old figure class and aligns as expected:
https://le.unimelb.edu.au/news/designing-for-learning-with-technology-may-workshops/

Note this site is using a custom WP theme with V 7.0 of DDS

**Comment by axelboc** [comment]
The image doesn't seem to be loading. Here it is with a placeholder:

<img width="1303" alt="screen shot 2017-09-22 at 9 16 29 am" src="https://user-images.githubusercontent.com/2936402/30722870-cd736b54-9f76-11e7-9dfc-a0912b018124.png">

The alignment of figures inside the [news-single](https://web.unimelb.edu.au/components/news/#news-single) component has indeed changed between v6 and v7. The change brings more consistency to the design of both the news-single and [event page](https://web.unimelb.edu.au/components/events/#multi-date-event-page) components. Notably, all figures now behave the same way, whether they contain images or [video embeds](https://web.unimelb.edu.au/components/news/#news-single-with-video).

**Comment by dcollett** [comment]
Oops. Should be there now.

**Comment by axelboc** [comment]
Ah I see, the problem is the size of the image. Any chance you could find a wider version? Needs to be at least 985px.

**Comment by dcollett** [comment]
Here's an example with a wider version:
https://le.unimelb.edu.au/news/get-ready-for-the-semester-2-subject-experience-survey-ses/
I guess I'm expecting it to resize to the column width, like the examples on https://web.unimelb.edu.au/components/figure/
![screen shot 2017-09-22 at 11 07 26 am](https://user-images.githubusercontent.com/1088483/30725207-41afe646-9f86-11e7-8bc3-979d627658d9.png)

**Comment by dcollett** [comment]
Hey Axel, it's not a bug so I'll close this. As you say the width of the image is the issue. Might be worth updating the caption on the image on this page:
https://web.unimelb.edu.au/components/news/#news-single
It gave me  the impression that 700px was OK as a min image width. That image is 1600px wide.
cheers,
Dean

**Comment by axelboc** [comment]
Ah yeah, well spotted! Will open a new issue, thanks.
